In [1]:
import numpy as np

In [ ]:
# Network model
def MSE(y,a):
    MSE = (1/10)*( np.sum( np.power( (y-a),2)))
    return MSE

def a_y(z):
    a_y = np.divide( np.exp(z), np.sum( np.exp(z)))
    return a_y

def z_y(w_y,a_2,b_y):
    w_y = np.transpose( w_y)
    b_y = np.transpose( b_y)
    z_y = np.add( np.sum(np.multiply(w_y,a_2),axis=1), b_y)
    return z_y

def a_2_nonvect(z_2):
    if z_2<0:
        z_2=0
    return z_2
a_2 = np.vectorize( a_2_nonvect)

def z_2(w_2,a_1,b_2):
    w_2 = np.transpose( w_2)
    b_2 = np.transpose( b_2)
    z_2 = np.add( np.sum(np.multiply(w_2,a_1),axis=1), b_2)
    return z_2

def a_1_nonvect(z_1):
    if z_1<0:
        z_1=0
    return z_1
a_1 = np.vectorize( a_1_nonvect)

def z_1(w_1,x,b_1):
    w_1 = np.transpose( w_1)
    b_1 = np.transpose( b_1)
    z_1 = np.add( np.sum(np.multiply(w_1,x),axis=1), b_1)
    return z_1

# Gradient descend
def indicator_nonvect(z):
    if z>0:
        z=1
    else:
        z=0
    return z
indicator = np.vectorize( indicator_nonvect)

def back_prop(z_1, w_2, z_2, w_y, a_y, y):
    DZ = np.array([[]])
    for i in range(a_y.shape[0]):
        DZ = np.append(DZ, np.sum( a_y*a_y[i]) - (a_y[i]*a_y[0])[0] + (a_y[i]*( 1-a_y[i]))[0])

    S_1 = np.multiply( ((-(y-a_y))/5), DZ)
    S_2 = np.multiply( np.multiply(S_1, w_y), indicator(z_2))
    S_3 = np.multiply( np.multiply( np.multiply( S_1,S_2), w_2), indicator(z_1))

    grad_w_y = np.multiply( S_1, a_2)
    grad_b_y = S_1
    grad_w_2 = np.multiply( np.multiply( S_1, S_2), a_1)
    grad_b_2 = np.multiply( S_1, S_2)
    grad_w_1 = np.multiply( np.multiply( np.multiply( S_1, S_2), S3), x)
    grad_b_1 = np.multiply( np.multiply( S_1, S_2), S3)
    return( grad_w_y, grad_b_y, grad_w_2, grad_b_2, grad_w_1, grad_b_1)

def grad_descend( epsilon, grad_w_y, grad_b_y, grad_w_2, grad_b_2, grad_w_1, grad_b_1):
    w_y = np.subtract( w_y, np.multiply(epsilon, grad_w_y))
    b_y = np.subtract( b_y, np.multiply(epsilon, grad_b_y))
    w_2 = np.subtract( w_2, np.multiply(epsilon, grad_w_2))
    b_2 = np.subtract( b_2, np.multiply(epsilon, grad_b_2))
    w_1 = np.subtract( w_1, np.multiply(epsilon, grad_w_1))
    b_1 = np.subtract( b_1, np.multiply(epsilon, grad_b_1))
    return( w_y, b_y, w_2, b_2, w_1, b_1)

In [107]:
a = np.array([[0,-4,3,4,5]])
b = np.array([[10,10,10,10,10]])
np.subtract(a, b)

array([[-10, -14,  -7,  -6,  -5]])

In [105]:
def test():
    a = np.array([[1,2,3,4,5]])
    b = np.array([[6,7,8,9,0]])
    c = np.array([[10,11,12,13,14]])
    return a,b,c
d,e,f = test()
print(d)
print(e)
print(f)

[[1 2 3 4 5]]
[[6 7 8 9 0]]
[[10 11 12 13 14]]
